version: "3.3"

services:
  postgres:
    container_name: recruitment
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rec123
      POSTGRES_DB: recruitment
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: