spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://0.0.0.0:5432/recruitment}
    username: ${SPRING_DATASOURCE_URL:root}
    password: ${SPRING_DATASOURCE_URL:rec123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:create-drop}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      file-size-threshold: 2MB

server:
  port: 7000
  error:
    include-message: always


logging:
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx

allowed:
  origin:
    url: "*"

security:
  signingKey: s2meBcgRWnODgza34+abFcStUXx49Ozju+Pd532YT1mfDMS8/Twv6wnjhLHdUJBkwbRoWP+N0vlBw4hSmY2HZ/WJYNRyOzD5f0wr3J3gyZC5fiWgs5lEJcygzTEvTufmRWPB10A8Est3o6co0lxom0ALe4q/mAU3046lm4T0QXDlazelWHVRbaYg07cHQGiIBGNJzEdi8CvzlsU3ArNiYgPw2fIREMVDM5axmg==
  algorithm: HS512
  validMinutes: 60
